title: Thiago Nascimento
description: .NET Engineer
baseurl: ""
url: https://thiagoftsn.github.io/

theme: cvless

# site settings
taglong: .NET Engineer
# tagshort: .NET Engineer

# author settings
author:
  name: Place Holder
  email: username@domain.com
photo: assets/files/photo.jpg
address: Foobar Hall 1.23
phone: +1 234 567 890

# profile links
profile:
  # facebook: https://www.facebook.com/username
  # x: https://x.com/username
  # mastodon: https://mastodon.social/@username
  # bluesky: https://bsky.app/profile/username.bsky.social
  # instagram: https://www.instagram.com/username
  linkedin: https://www.linkedin.com/in/thiagoftsn
  # xing: https://www.xing.com/profile/username
  # stackoverflow: https://stackoverflow.com/users/0000000/username
  # medium: https://medium.com/@username
  github: https://github.com/thiagoftsn

# build settings
permalink: pretty
exclude:
  - LICENSE
  - README.md
  - Gemfile
  - vendor/
  - docker-compose.yml

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never
  
